language: python
python:
  - "2.7.13"
  - "3.6"
env:
  global:
    - MONGO_URL=mongodb://localhost
    - MONGO_PORT=27017
    - SS_USER=http://www.mocky.io/v2/5ad6e0fc2e00002b00c93c3d
  matrix:
    - SS_TOKEN=http://www.mocky.io/v2/5ad6e0fc2e00002b00c93c3d
services:
  - mongodb
install:
  - pip install -r requirements-test.txt
script: 
  - pytest --cov-config .coveragerc --cov=$(pwd)
after_success:
  - coveralls