language: python
python:
  - "2.7.13"
  - "3.6"
env: 
  - "MONGO_URL=mongodb://localhost/"
services:
  - mongodb
install:
  - pip install -r requirements-test.txt
script: 
  - pytest --cov-config .coveragerc --cov=$(pwd)
after_success:
  - coveralls