language: python
python:
  - "2.7.13"
  - "3.6"
services:
  - mongodb
install:
  - pip install -r requirements-test.txt
before_script:
  - sleep 15
script: 
  - pytest --cov-config .coveragerc --cov=$(pwd)
after_success:
  - coveralls