sudo: required
language: python
python:
- "3.6"
env:
  global:
  - MONGO_URL=mongodb://localhost
  - MONGO_PORT=27017
services:
- mongodb
- docker
install:
- pip install -r requirements-test.txt
script:
- pytest --cov-config .coveragerc --cov=$(pwd)
after_success:
- coveralls
deploy:
  provider: script
  script:
    - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
    - docker build -t registry.heroku.com/app-server-stories/web .
    - docker push registry.heroku.com/app-server-stories/web
  on:
    branch: docker_to_heroku
    repo: taller2-2018-1-grupo2/python-server
