language: python
python:
  - "2.7.13"
  - "3.6"
env:
  - $PYTHONPATH=../
install:
  - pip install -r requirements-test.txt
script: 
  - pytest --cov-config .coveragerc --cov=$(pwd)
after_success:
  - coveralls