swagger: "2.0"
info:
  description: API para el shared server de Stories
  version: 1.0.0
  title: Stories - Aplication Server API
host: virtserver.swaggerhub.com
basePath: /nicotruk/ApplicationServerAPI/1.0.0
tags:
- name: ping
  description: |
    Llamados de verificacion de conexiones a los servidores
- name: users
  description: |
    Llamados relacionados con el login y la registracion de usuarios
schemes:
- https
- http
consumes:
- application/json
produces:
- application/json
paths:
  /ping:
    get:
      tags:
      - ping
      summary: Conexion a Application Server
      description: Chequea conexion a Application Server
      parameters: []
      responses:
        200:
          description: Conectado
  /ping/sharedServer:
    get:
      tags:
      - ping
      summary: Conexion a Shared Server
      description: Chequea conexion a Shared Server
      parameters: []
      responses:
        200:
          description: Conectado
        404:
          description: Conexion a Shared Server fallida
definitions: {}