FIREBASE_NOTIFICATIONS_ENABLED = True
NOTIFICATION_TYPE_MESSAGE = "message"

NOTIFICATION_TYPE_FRIENDSHIP_REQUEST = "friendship_request"
NOTIFICATION_TYPE_FRIENDSHIP_REQUEST_MESSAGE = "Nueva solicitud de amistad"

NOTIFICATION_TYPE_STORY = "story"
NOTIFICATION_TYPE_STORY_MESSAGE = "Nueva historia publicada"


